### ISSUE TITLE
0.3.2 release tag

### ISSUE THREAD

**Issue by Rich-Harris** [padolsey/operative#28]
Hi, any chance you could push a new release tag for those of us who have to use Bower? Copy & pasting this should do the trick:

```bash
git checkout master
git tag -a v0.3.2 -m 'version 0.3.2'
git push origin v0.3.2
```

Thanks

**Comment by padolsey** [comment]
Ah, sorry about that. Tagged: https://github.com/padolsey/operative/releases/tag/0.3.2

**Comment by Rich-Harris** [comment]
:+1:
