### ISSUE TITLE
Lacking support for CommonJS

### ISSUE THREAD

**Issue by rileyjshaw** [padolsey/operative#33]
Operative [plays nice with AMD](https://github.com/padolsey/operative/blob/857a6e94c8ffccd5925d5dbcfe9fe4f944dff51a/dist/operative.js#L20) but resorts to a global in CommonJS loaders. [Here's an example](https://github.com/umdjs/umd/blob/master/returnExports.js) of a Universal Module Definition that covers all bases.

**Comment by padolsey** [comment]
Hmm yeh should probably get this in. Thanks for opening an issue! Up for putting together a PR?

**Comment by rileyjshaw** [comment]
@padolsey done! Sorry for the delay :)

**Comment by padolsey** [comment]
Thanks!!

**Comment by rileyjshaw** [comment]
No worries :)

**Comment by rileyjshaw** [comment]
Hey @padolsey - bad news :(

Because some of the submodules (eg. OperativeContext.js) are relying on the global `operative`, this still doesn't work well in a bundle. I see two routes from here:

 1. Remove checks for both AMD and CommonJS, create a global `operative` by default, and leave the Grunt concatenation untouched.
 2. Rewrite the modules to use AMD or CommonJS, and bundle them with something like [grunt-browserify](https://github.com/jmreidy/grunt-browserify).

Option 1 has the advantage of minimizing change to the library, and removes the need for more complex bundlers (it's just concatenated .js files). Option 2 has the advantage of allowing the library to be consumed transparently by any client, and removing an unnecessary global in bundled settings.

Sorry to bring this back up - I thought https://github.com/padolsey/operative/pull/34 was sufficient, but I hadn't considered the other files that are concatenated with operative.js...

**Comment by rileyjshaw** [comment]
I can make a PR for either option, just wanted to get your thoughts before moving ahead.

**Comment by padolsey** [comment]
Ah, yep, I should have noticed that. Definitely up for option #2 if you have the time. The concatenation is a bit of a mess now.

**Comment by rileyjshaw** [comment]
Though option 2 has obvious benefits, lines like [this](https://github.com/padolsey/operative/blob/a6be10de10076b7f41952af84ea5cf63ae45d57e/src/contexts/Iframe.js#L117-L118) might make it pretty hard to remodel. For the time being I think that unbreaking things quickly with a global is the right course of action.

Let me know what you think! Sorry this wasn't as easy as I'd initially thought.

**Comment by rileyjshaw** [comment]
(see https://github.com/padolsey/operative/pull/38)

**Comment by padolsey** [comment]
That `__run__` would only be exposed in the generated iframe, but I still agree that this all might be more trouble than it's worth (at least at the moment). Shall look into your PR.

**Comment by padolsey** [comment]
(Closing for now; I would very much like to revisit this at some point though)
