### ISSUE TITLE
operative... ROCKS!

### ISSUE THREAD

**Issue by robertleeplummerjr** [padolsey/operative#40]
Just thought I'd chime in and say this lib is fantastic.  We were able to stream several hundred meg of json into the browser in under a second with no browser freeze using this concept: https://gist.github.com/robertleeplummerjr/b17b900fb50f786c78df

rock on multi threading!

**Comment by sterpe** [comment]
Is there any demo page to see this in action?

**Comment by padolsey** [comment]
Awesome! (Glad you found operative useful :+1:)
