### ISSUE TITLE
Try/catch within a function seems to break operative?

### ISSUE THREAD

**Issue by alan-unravel** [padolsey/operative#42]
Not sure why this would be the case can anyone shine some light on this? Thanks in advance.

**Comment by padolsey** [comment]
Throwing/Trying/Catching seems to work intuitively within an operative, see: http://jsbin.com/yayayanuho/edit?html,js,output

Could you paste an example of it breaking?

**Comment by alan-unravel** [comment]
Sure apologies if this is some silly mistake
```
 "dimension.group.reduceSum": function(index, accessor) {
    var promise = this.deferred();
    try
    {
      this.dimensionGroups[index].reduceSum(this.unpack(accessor));
      promise.fulfill();
    } catch (e){
      promise.reject();
    }
}
```

**Comment by alan-unravel** [comment]
Hey guys sorry, it was a mistake on my part compounded together with a different issue. Thanks! Great library btw
